version: '3'
services:
  frontend:
    image: buildbarn/bb-storage:20220718T171335Z-35abb67
    command:
    - /config/frontend.jsonnet
    expose:
    - 9980
    ports:
    - 8980:8980
    volumes:
    - ./config:/config

  storage-0:
    image: buildbarn/bb-storage:20220718T171335Z-35abb67
    command:
    - /config/storage.jsonnet
    expose:
    - 8981
    - 9980
    volumes:
    - ./config:/config
    - ./storage-ac-0:/storage-ac
    - ./storage-cas-0:/storage-cas

  storage-1:
    image: buildbarn/bb-storage:20220718T171335Z-35abb67
    command:
    - /config/storage.jsonnet
    expose:
    - 8981
    - 9980
    volumes:
    - ./config:/config
    - ./storage-ac-1:/storage-ac
    - ./storage-cas-1:/storage-cas

  scheduler:
    image: buildbarn/bb-scheduler:20220711T053610Z-2f8fb05
    command:
    - /config/scheduler.jsonnet
    expose:
    - 8982
    - 8983
    - 9980
    ports:
    - 7982:7982
    volumes:
    - ./config:/config

  browser:
    image: buildbarn/bb-browser:20220702T043727Z-002b284
    command:
    - /config/browser.jsonnet
    expose:
    - 9980
    ports:
    - 7984:7984
    volumes:
    - ./config:/config

  worker-ubuntu22-04:
    image: buildbarn/bb-worker:20220711T053610Z-2f8fb05
    command:
    - /config/worker-ubuntu22-04.jsonnet
    ports:
    - 7986:7986
    volumes:
    - ./config:/config
    - ./worker-ubuntu22-04:/worker

  runner-ubuntu22-04:
    image: ghcr.io/catthehacker/ubuntu:act-22.04@sha256:5f9c35c25db1d51a8ddaae5c0ba8d3c163c5e9a4a6cc97acd409ac7eae239448
    command:
    - sh
    - -c
    - while ! test -f /bb/installed; do sleep 1; done; exec /bb/tini -v -g -- /bb/bb_runner /config/runner-ubuntu22-04.jsonnet
    volumes:
    - ./worker-ubuntu22-04:/worker
    - ./config:/config
    - ./bb:/bb
    depends_on:
    - runner-installer

  runner-installer:
    image: buildbarn/bb-runner-installer:20220711T053610Z-2f8fb05
    volumes:
    - ./bb:/bb
