apiVersion: v1
data:
  worker-ubuntu22-04.jsonnet: |
    local common = import 'common.libsonnet';

    {
      blobstore: common.blobstore,
      browserUrl: common.browserUrl,
      maximumMessageSizeBytes: common.maximumMessageSizeBytes,
      scheduler: { address: 'scheduler:8983' },
      maximumMemoryCachedDirectories: 1000,
      global: common.global + {
        setUmask: { umask: 0 },
      },
      buildDirectories: [{
        native: {
          buildDirectoryPath: '/worker/build',
          cacheDirectoryPath: '/worker/cache',
          maximumCacheFileCount: 10000,
          maximumCacheSizeBytes: 1024 * 1024 * 1024,
          cacheReplacementPolicy: 'LEAST_RECENTLY_USED',
        },
        runners: [{
          endpoint: { address: 'unix:///worker/runner' },
          concurrency: 8,
          platform: {
            properties: [
              { name: 'OSFamily', value: 'Linux' },
            ],
          },
        }],
      }],
      outputUploadConcurrency: 11,
    }
kind: ConfigMap
metadata:
  name: worker-ubuntu22-04
  namespace: buildbarn
